"""Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

"""

# Generator to generate the triangle, pentagonal, and hexagonal numbers
def get_nums():
	n = 1
	while True:
		t_num = int(n * (n + 1) / 2)
		p_num = int(n * (3*n - 1) / 2)
		h_num = int(n * (2*n - 1))
		n += 1
		yield t_num, p_num, h_num


if __name__ == "__main__":
	n = 1
	t_set = set()
	p_set = set()
	h_set = set()
	
	stop = False
	stop_adding = 100
	nums_gen = get_nums()
	# Loop and add more numbers in the set until required answer is not found
	while not stop:
		for t, p, h in nums_gen:
			t_set.add(t)
			p_set.add(p)
			h_set.add(h)
			if n > stop_adding:
				break
			n += 1
		
		for t in t_set:
			if t in p_set and t in h_set and t > 40755:
				print(t)
				stop = True

		n = 1


